# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_app_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Comp_app_algo import Ui_Comp_app
import re

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 783)
        Form.setStyleSheet("*{\n"
"    font-famly:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"    background:#333;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"#Form\n"
"{\n"
"    background: #333;\n"
"\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: #333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: #717072;\n"
"    border-bottom:1px solid #717072;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(110, 100, 511, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 70, 171, 51))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.Login = QtWidgets.QPushButton(self.frame)
        self.Login.setGeometry(QtCore.QRect(20, 580, 471, 51))
        self.Login.setObjectName("Login")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(50, 160, 381, 41))
        self.username.setText("")
        self.username.setObjectName("username")
        self.Password = QtWidgets.QLineEdit(self.frame)
        self.Password.setGeometry(QtCore.QRect(50, 490, 381, 41))
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Email = QtWidgets.QLineEdit(self.frame)
        self.Email.setGeometry(QtCore.QRect(50, 270, 381, 41))
        self.Email.setText("")
        self.Email.setObjectName("Email")
        self.Phone = QtWidgets.QLineEdit(self.frame)
        self.Phone.setGeometry(QtCore.QRect(50, 390, 381, 41))
        self.Phone.setText("")
        self.Phone.setObjectName("Phone")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 171, 51))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 230, 171, 51))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 350, 171, 51))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 450, 171, 51))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(280, 20, 131, 131))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icn_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(128, 128))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)







    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "App"))
        self.label.setText(_translate("Form", "LOGIN HERE"))
        self.Login.setText(_translate("Form", "Login"))
        self.username.setPlaceholderText(_translate("Form", "User Name"))
        self.Password.setPlaceholderText(_translate("Form", "Password"))
        self.Email.setPlaceholderText(_translate("Form", "Email "))
        self.Phone.setPlaceholderText(_translate("Form", "Phone Number"))
        self.label_2.setText(_translate("Form", "User Name"))
        self.label_3.setText(_translate("Form", "Email Adress"))
        self.label_4.setText(_translate("Form", "Phone number"))
        self.label_5.setText(_translate("Form", "Password"))

        # Connection

        self.Login.clicked.connect(self.log_in)

    def log_in(self):
        user_names = ['Elubai', 'Zhansaya', 'Aygerim']
        Email_check = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
        password_check = re.compile(r'^.*(?=.{8,10})(?=.*[a-zA-Z])(?=.*?[A-Z])(?=.*\d)[a-zA-Z0-9!@£$%^&*()_+={}?:~\[\]]+$')
        if self.username.text() in user_names:
            if re.fullmatch(Email_check, self.Email.text()):
                if re.match(r'[1-9]{1}[0-9]{9}', self.Phone.text()) and len(self.Phone.text()) == 11:
                    if re.fullmatch(password_check, self.Password.text()):
                        self.Form = QtWidgets.QWidget()
                        self.ui = Ui_Comp_app()
                        self.ui.setupUi(self.Form)
                        self.Form.show()
                    else:
                        self.username.setText('Incorrect password')
                else:
                    self.Phone.setText('Incorrect phone number')
            else:
                self.Email.setText('Incorrect email')
        else:
            self.username.setText('Incorrect name')




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
